server:
  port: 8080
  servlet:
    session:
      timeout: 28800
#  servlet:
#    context-path: "/ho-api"
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456My!
    url: jdbc:mysql://121.41.226.28:3306/hotel?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
mybatis:
  type-aliases-package: classpath*:cn.mafangui.hotel.entity
  mapper-locations: classpath*:mybatis/mapper/*.xml
alipay:
  appId: 9021000135607213
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCytSpfJRrbfnjLULm1moqVFyljnzX8Mrt4jRg6q+cqiSMAVhkNHy8UCTqd2/J9AEFNKHRiptpyxt6xb4rBtUFytCntZOPQwtIpNDSr5f0HK3uIsL/5YHt0OTeR8iNOo89Z38RswyA3L10y/Wh0siTr9IhlBAkulFEOfhuJyPt9NRB77RVMZ6hzJwsFp8KUUdSKhQ1D5FZG6gbsbsjO9wPcHiaLQXGX2ORNJPo/PQoYVMRYWouU7zWF7RSTRS1OEobtU21moMOBPSjBpvOx0feLSoJQbbl5u171zQl7jH2hfIvSr1P5QGBFEFFCAjUnz2ZJQ3Myr3loS8wW5Kjv5sTfAgMBAAECggEAeDhX4NndT3utV1lfFUR5pgKG3XXlo1udsmN4wT+Tq5HF8hv5jlJEIX5z6G5mmqDpTTbB1PvaSQxwE32uItIEzV1WN1V/zJjDOOTd6iY2KfSejj4ZZ3H4mx9CuvPhvK2GeDeItIIv0fATCpJfCuIs5G8EsrAcXTF5tf4wGGkUhg1gcXKX0Qjt0qxZe+cGXEehHLzjO9X8ShuzZvZcZtu0mmTiOXeaY02U7lHbjJQe5lXbMZjhHaNyO8O6F9kDRmW4Mehz899VJmcoFVKLqldtAdyZMV4ROBatvaiCuZ/5pnq5yQ/ar+Kj2kdVjncVbBbX/oAxEDXmrTCC3iHnpKRPAQKBgQD+vW5hyfwjwgZ7X7grh+Ipgb+0G0OhbKDSoUWZH44PpnziwHdWJ6931oTYr8Mj7kmE1WL4jJReCnUQVvHbN4wpZV2nhOexLnD3uH9kl7HncYR4CWKn9r0rIOAAOK810zV9/IVP8Ji9TRHVlQIlg2408KRKStkg511Dzwt8LYxx8QKBgQCzl3UIH/uTBlrhoq5nal/7dvfLwMC2Jx5X0HguudCRyZ5/TrRAiW6i+dxqaDnGPLC0BIvJ5tYI3a5sx5J6XaNQP3GgvbQAl3nXB/pa3GsWaSbUW6BCTC334f0+8qvtyioQ7Um4mKxaYZvRoDLncTXr9iQn7YKw7mzWJJwOYz3TzwKBgHH0QZ2jIpTIZefo0NVASw6wSRaDn8RleKfglubBs+YSXwl8eaXjyN29692W+p9nKCIw5r4y/Of4m5d8nWKoPZ4DB1s52/9pvAVE1lAkf+P95vlfkW97s/HIGgxfTxmv6tz6CpTRFzKPeGvn5XbsjW9HOuc1Bl5uwUzlIMkjAxGxAoGBAK5RvAJH8QxT5dEP9FNjOIlAf+PhU+066UP5kT5hlGZ+Gn+d6G6gN6iv+Ne8FSArdqU1qG4wxt5SNuVVjgOCcmwJOQT6Pgc5AMXM86BQRQ26wTrtORBBG3l5fTQlnuawDcbiXGV2pA0So4mFAwQNqnZAM/Yhn3KX60KsxGFeyPuXAoGAcf4e+N6jp+MiubOjblq1PISa3D9CQLrszQJ6YbJL0r0ZaawSWTobAtRWdx5iuhPKkz2gAjiPJ3UyXoQA43cJ+/6Uz9iEg7fW+lY3nRgw1hj0mB/wHoQUmj4083srziOny80fjelP85kyoM2MHswq63TPvGIozzw2H3lXURjFM3g=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2OabIBZrAeKU7yVXNdMb1b0COsjDnMBDhEeTq0E6Q5z6NUS/gFqwDBr7NrGeBsRJIqfCPjZIYZVdsF/Vrf5fdrFvvCZEM7bFXLA60OviUi9ZWu7gAnNw94cA4VBx3FEPEbGPZfK33lcw8pdOLl73hLG2XE5S0y6zumXqdRL376wkIR2dPNkM1wGOXNNPNeMPDemcW0g/3EGzhhz696kqbogi0XkKVET2Yjdxf+Me5X+pbL1CkLs9s/fL+bn5SN9Qot5RXvzOsGs3DmSFEvByUAVm/ti0EgfkBTnI7xyS4CL2a1Tvf5zSCvEhR3OAGFvk6t+hSDWtf32Y/EftFX2gOwIDAQAB
  notifyUrl:  http://121.41.226.28:8080/alipay/notify
  # notifyUrl:  http://96crre.natappfree.cc/alipay/notify

